.PHONY: clean build run

build:
	@echo "Building..."
	@go build -o bin/jasper main.go
	@echo "Done!"
clean:
	@echo "Cleaning up..."
	@rm bin/jasper
	@echo "Done!"
run:
	@echo "Running..."
	@bin/jasper
